Task exception was never retrieved
future: <Task finished coro=<BDLoop.bday_loop() done, defined at /home/evan/Botto/funcs/bday_loop.py:19> exception=AttributeError("'Object' object has no attribute 'server'",)>
Traceback (most recent call last):
  File "/home/evan/Botto/funcs/bday_loop.py", line 27, in bday_loop
    await asyncio.gather(*all_channels)
  File "/home/evan/Botto/funcs/bday_loop.py", line 35, in _get_bdays
    time = self.gdb.get_guild_birthday_announcement_time(bdchannel.server.id)[0]
AttributeError: 'Object' object has no attribute 'server'
Failing the WebSocket connection: 1006 
ibuteError: 'Object' object has no attribute 'server'
/home/pi/Botto/funcs/bday_loop.py:19> exception=AttributeError("'Object' object has no attribute 'server'",)>
Traceback (most recent call last):
  File "/home/pi/Botto/funcs/bday_loop.py", line 27, in bday_loop
    await asyncio.gather(*all_channels)
  File "/home/pi/Botto/funcs/bday_loop.py", line 35, in _get_bdays
    time = self.gdb.get_guild_birthday_announcement_time(bdchannel.server.id)[0]
AttributeError: 'Object' object has no attribute 'server'
    yield from self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 458, in _wait_for_data
    yield from self._waiter
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
